### ISSUE TITLE
Some issues with some invocations

### ISSUE THREAD

**Issue by szaumoor** [ArtemiusI/Warlock#2]
Tested in BG2EE SoA.

- When using Devil's Sight, the log states constantly that the caster is "unaffected by effects from devil's sight".
- When learning Dark invocations, "Word of Changing" appears several times in the dialog box.
- When using a hellfire blast with a Doom shape, there is no constitution drain.
- When using a hellfire blast with a Chain shape, the log says "Invalid: 106943" after targeting a neutral NPC (Jaheira).
- When using hellfire blast with Hideous Blow, nothing happens after attacking.

**Comment by TheArtisanBG** [comment]
Went through the mod with an overhaul of the blast shapes and all these should be fixed now.
